'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Activity, ArrowUpRight, BarChart3, BriefcaseBusiness, CheckCircle2, CircleDollarSign, Database, FileText, LayoutDashboard, RefreshCw, ShieldCheck, Users } from 'lucide-react';
import type { OwnerOverview } from '@/lib/admin/owner-types';

const formatNumber = (value: number | null | undefined) => value == null ? '—' : value.toLocaleString('pt-BR');
const formatDate = (value: string) => new Date(value).toLocaleString('pt-BR', { dateStyle: 'short', timeStyle: 'short', timeZone: 'America/Sao_Paulo' });
const statusLabels: Record<string, string> = { open: 'Aberto', in_progress: 'Em andamento', closed: 'Encerrado', cancelled: 'Cancelado', freelancer: 'Profissional', client: 'Cliente', both: 'Cliente e profissional' };

function Metric({ title, value, detail, icon: Icon }: { title: string; value: number | null | undefined; detail: string; icon: typeof Users }) {
  return <article className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-sm font-medium text-slate-600">{title}</h2><Icon className="size-5 text-blue-600" /></div><p className="mt-5 text-3xl font-semibold tracking-tight text-slate-900">{formatNumber(value)}</p><p className="mt-2 text-xs leading-5 text-slate-500">{detail}</p></article>;
}

export function AdminDashboardClient({ viewer, role }: { viewer: string; role: string }) {
  const [days, setDays] = useState(30);
  const [data, setData] = useState<OwnerOverview | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [autoRefresh, setAutoRefresh] = useState(true);
  const activeRequest = useRef<AbortController | null>(null);

  const load = useCallback(async () => {
    activeRequest.current?.abort();
    const controller = new AbortController(); activeRequest.current = controller;
    setLoading(true); setError(null);
    try {
      const response = await fetch(`/api/admin/overview?days=${days}`, { cache: 'no-store', signal: controller.signal });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || 'Não foi possível atualizar os indicadores.');
      if (!controller.signal.aborted) setData(result);
    } catch (failure) {
      if (!controller.signal.aborted) setError(failure instanceof Error ? failure.message : 'Não foi possível atualizar os indicadores.');
    } finally { if (!controller.signal.aborted) setLoading(false); }
  }, [days]);

  useEffect(() => {
    const initialLoad = setTimeout(() => { void load(); }, 0);
    const timer = autoRefresh ? setInterval(() => { if (document.visibilityState === 'visible') void load(); }, 60000) : null;
    return () => { clearTimeout(initialLoad); if (timer) clearInterval(timer); activeRequest.current?.abort(); };
  }, [load, autoRefresh]);

  const counts = data?.counts;
  const unavailable = !data || data.state === 'not_configured';
  const planRows = [{ label: 'Grátis', count: counts?.free }, { label: 'Pro', count: counts?.pro }, { label: 'Business', count: counts?.business }];
  const totals = planRows.reduce((sum, item) => sum + (item.count ?? 0), 0);
  return <div className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:py-10">
    <div className="flex flex-wrap items-center justify-between gap-5"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-blue-700"><ShieldCheck className="size-4" />Área exclusiva do dono</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Seu negócio, em uma visão.</h1><p className="mt-3 text-sm text-slate-500">{viewer} · {role === 'super_admin' ? 'Proprietário' : 'Administrador'}</p></div><Link href="/" className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 text-sm font-medium">Ver site<ArrowUpRight className="size-4" /></Link></div>
    <nav aria-label="Seções do painel" className="mt-7 flex gap-2 overflow-x-auto border-b border-slate-200 pb-4 text-sm">{[['#visao-geral', 'Visão geral'], ['#planos-admin', 'Planos e pagamentos'], ['#atividade-admin', 'Atividade'], ['#integracoes-admin', 'Integrações'], ['/admin/leads', 'Leads das landings']].map(([href, label]) => <a key={href} href={href} className="whitespace-nowrap rounded-lg px-4 py-2 text-slate-600 hover:bg-white hover:text-blue-700">{label}</a>)}</nav>
    <div className="my-6 flex flex-wrap items-center justify-between gap-4"><p role="status" className="text-xs text-slate-500">{loading ? 'Atualizando indicadores…' : data ? `Última consulta: ${formatDate(data.generatedAt)}` : 'Nenhuma consulta concluída'}</p><div className="flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={autoRefresh} onChange={event => setAutoRefresh(event.target.checked)} />Atualizar a cada minuto</label><label className="sr-only" htmlFor="owner-period">Período dos indicadores</label><select id="owner-period" value={days} onChange={event => { setData(null); setDays(Number(event.target.value)); }} className="min-h-11 rounded-lg border border-slate-200 bg-white px-3 text-sm">{[7, 30, 90].map(day => <option key={day} value={day}>Últimos {day} dias</option>)}</select><button type="button" onClick={() => void load()} disabled={loading} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-blue-600 px-4 text-sm font-semibold text-white hover:bg-blue-700 disabled:opacity-50"><RefreshCw className={`size-4 ${loading ? 'animate-spin' : ''}`} />Atualizar</button></div></div>
    {error && <p role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}{data ? ' Os dados abaixo são da última consulta concluída.' : ''}</p>}
    {data?.state === 'not_configured' && <div className="mb-6 flex gap-3 rounded-xl border border-blue-200 bg-blue-50 p-5"><Database className="mt-1 size-5 shrink-0 text-blue-700" /><div><h2 className="font-semibold text-blue-950">Painel pronto. Conexão administrativa pendente.</h2><p className="mt-2 text-sm leading-6 text-blue-900">Os indicadores aparecem quando o acesso privado ao Supabase for configurado. “—” significa indisponível; zero será mostrado apenas quando a consulta retornar zero.</p></div></div>}
    <section id="visao-geral" className="scroll-mt-28 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <Metric title="Perfis cadastrados" value={counts?.profiles} detail="Total de perfis na plataforma" icon={Users} /><Metric title="Projetos abertos" value={counts?.openProjects} detail="Projetos com status aberto agora" icon={BriefcaseBusiness} /><Metric title="Serviços ativos" value={counts?.activeServices} detail="Serviços publicados e ativos" icon={LayoutDashboard} /><Metric title="Propostas enviadas" value={counts?.proposals} detail="Total registrado na plataforma" icon={FileText} />
      <Metric title="Novos perfis" value={counts?.newProfiles} detail={`Criados nos últimos ${days} dias`} icon={Users} /><Metric title="Novos projetos" value={counts?.newProjects} detail={`Publicados nos últimos ${days} dias`} icon={BriefcaseBusiness} /><Metric title="Novas propostas" value={counts?.newProposals} detail={`Enviadas nos últimos ${days} dias`} icon={Activity} /><Metric title="Propostas aceitas" value={counts?.acceptedProposals} detail={`Criadas no período e atualmente aceitas`} icon={CheckCircle2} />
    </section>
    <section id="planos-admin" className="mt-7 grid scroll-mt-28 gap-5 lg:grid-cols-2"><article className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Planos registrados nos perfis</h2><p className="mt-2 text-sm leading-6 text-slate-500">A distribuição abaixo representa o cadastro atual. Ela não comprova pagamentos recebidos.</p><div className="mt-6 space-y-5">{planRows.map(item => <div key={item.label}><div className="flex justify-between text-sm"><span className="font-medium">{item.label}</span><span>{formatNumber(item.count)}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: item.count == null || totals === 0 ? '0%' : `${item.count / totals * 100}%` }} /></div></div>)}</div><p className="mt-6 border-t border-slate-100 pt-4 text-sm text-slate-600">Registros de assinatura pendentes de vínculo: <strong>{formatNumber(counts?.pendingSubscriptions)}</strong></p></article><article className="rounded-xl border border-slate-200 bg-white p-6"><CircleDollarSign className="size-6 text-blue-600" /><h2 className="mt-4 text-lg font-semibold">Receita e pagamentos</h2><p className="mt-4 text-4xl font-semibold">—</p><p className="mt-3 text-sm leading-7 text-slate-600">A conciliação financeira do Assiny ainda precisa ser concluída. Receita recebida, recorrência, cancelamentos e reembolsos só devem ser exibidos com registros confirmados do provedor.</p><div className="mt-5 rounded-lg bg-slate-50 p-4 text-sm text-slate-600">Novas assinaturas: <strong>{data ? data.integrations.checkout ? 'Configuração habilitada' : 'Em preparação' : 'Verificando'}</strong></div><Link href="/plans" className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-blue-700">Ver apresentação dos planos<ArrowUpRight className="size-4" /></Link></article></section>
    <section id="atividade-admin" className="mt-7 grid scroll-mt-28 gap-5 xl:grid-cols-2"><article className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Últimos perfis cadastrados</h2><div className="mt-4 divide-y divide-slate-100">{data?.recentProfiles.map(profile => <div key={profile.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="text-sm font-medium">{profile.full_name || 'Perfil sem nome'}</p><p className="mt-1 text-xs text-slate-500">{statusLabels[profile.role || ''] || profile.role || 'Tipo não informado'}{profile.city ? ` · ${profile.city}` : ''}</p></div><span className="text-xs text-slate-500">{formatDate(profile.created_at)}</span></div>)}{!data?.recentProfiles.length && <p className="py-8 text-sm text-slate-500">{unavailable || data?.state === 'partial' ? 'Lista indisponível até a consulta ao banco ser concluída.' : 'Nenhum perfil encontrado.'}</p>}</div></article><article className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Últimos projetos publicados</h2><div className="mt-4 divide-y divide-slate-100">{data?.recentProjects.map(project => <div key={project.id} className="py-4"><Link href={`/projects/${project.id}`} className="text-sm font-medium text-blue-700 hover:underline">{project.title}</Link><p className="mt-2 text-xs text-slate-500">{statusLabels[project.status] || project.status} · {formatDate(project.created_at)}</p></div>)}{!data?.recentProjects.length && <p className="py-8 text-sm text-slate-500">{unavailable || data?.state === 'partial' ? 'Lista indisponível até a consulta ao banco ser concluída.' : 'Nenhum projeto encontrado.'}</p>}</div></article></section>
    <section id="integracoes-admin" className="mt-7 grid scroll-mt-28 gap-5 lg:grid-cols-2"><article className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">Configuração das integrações</h2><p className="mt-2 text-xs leading-6 text-slate-500">Presença da configuração no servidor. A confirmação de funcionamento exige a validação de cada integração.</p><div className="mt-4 divide-y divide-slate-100">{[['database', 'Acesso administrativo ao banco'], ['webhook', 'Autenticação do webhook Assiny'], ['checkout', 'Liberação de novas assinaturas'], ['analytics', 'Google Analytics'], ['searchConsole', 'Verificação do Google Search Console']].map(([key, label]) => <div key={key} className="flex items-center justify-between gap-4 py-4 text-sm"><span>{label}</span><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-medium ${data?.integrations[key as keyof OwnerOverview['integrations']] ? 'bg-blue-50 text-blue-700' : 'bg-slate-100 text-slate-500'}`}>{!data ? '—' : data.integrations[key as keyof OwnerOverview['integrations']] ? 'Configurado' : 'Pendente'}</span></div>)}</div></article><article className="rounded-xl border border-slate-200 bg-white p-6"><BarChart3 className="size-6 text-blue-600" /><h2 className="mt-4 text-lg font-semibold">Aquisição, conversão e SEO</h2><p className="mt-3 text-sm leading-7 text-slate-600">A página inicial registra cliques para contratar, cliques para criar perfil e envio da busca no Google Analytics, quando o visitante autoriza a medição. Visitas e conversão não são estimadas a partir dos cadastros.</p><div className="mt-5 flex flex-wrap gap-3"><a href="https://analytics.google.com/" target="_blank" rel="noreferrer" className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-medium text-blue-700">Abrir Analytics ↗</a><a href="https://search.google.com/search-console" target="_blank" rel="noreferrer" className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-medium text-blue-700">Search Console ↗</a><a href="/sitemap.xml" className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-medium">Sitemap</a></div></article></section>
    {data && <section className="mt-7 rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-lg font-semibold">O que precisa de atenção</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{data.notices.map(notice => <div key={notice.title} className="border-l-2 border-blue-200 pl-4"><h3 className="text-sm font-semibold">{notice.title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{notice.description}</p></div>)}</div></section>}
  </div></div>;
}
