import Link from "next/link";
import { ArrowRight, Check, Gift, ShieldCheck, Users, Wallet } from "lucide-react";
import { getPageMetadata } from "@/lib/seo/metadata";

export const metadata = getPageMetadata(
  "Programa Partner PrestaCerto | Indique e receba por Pix",
  "Indique clientes e profissionais para o PrestaCerto, acompanhe a conversão e solicite sua recompensa após a validação.",
  "/parceiros",
);

const stages = [
  ["01", "Cadastro", "Entre ou crie sua conta e acesse o painel de indicações."],
  ["02", "Indicação", "Compartilhe seu link com alguém para quem o PrestaCerto realmente faça sentido."],
  ["03", "Validação", "A equipe confirma pagamento, duplicidade e elegibilidade antes do Pix."],
];

const steps = [
  ["Crie seu link", "Gere um link direto no painel do parceiro."],
  ["Apresente a plataforma", "Explique o benefício com clareza, sem prometer resultado."],
  ["Acompanhe o status", "Veja as indicações registradas e o andamento da validação."],
  ["Receba por Pix", "Após a aprovação, a recompensa entra na fila de pagamento manual."],
];

export default function PartnersPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-7 sm:px-8">
        <Link href="/" className="text-xl font-black tracking-tight">presta<span className="text-blue-400">certo</span></Link>
        <div className="flex items-center gap-3"><Link href="#como-funciona" className="hidden text-sm font-semibold text-slate-300 hover:text-white sm:block">Como funciona</Link><Link href="/login?next=%2Fdashboard%2Freferral" className="rounded-full border border-white/20 px-4 py-2 text-sm font-bold transition hover:bg-white/10">Entrar</Link></div>
      </header>
      <section className="mx-auto max-w-6xl px-5 pb-20 pt-10 sm:px-8 sm:pt-20">
        <div className="grid items-center gap-12 lg:grid-cols-[1.08fr_.92fr]">
          <div><p className="text-xs font-bold uppercase tracking-[0.22em] text-blue-300">PROGRAMA PARTNER PRESTACERTO</p><h1 className="mt-5 max-w-3xl text-4xl font-black tracking-tight sm:text-6xl">Boas indicações merecem uma recompensa clara.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Apresente o PrestaCerto a clientes, profissionais e parceiros que precisam contratar ou oferecer serviços. Você acompanha a indicação e recebe quando a conversão elegível é confirmada.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/register?next=%2Fdashboard%2Freferral" className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-500 px-6 py-3.5 font-bold transition hover:bg-blue-400">Quero ser parceiro <ArrowRight className="size-5" /></Link><Link href="#como-funciona" className="inline-flex items-center justify-center rounded-xl border border-white/20 px-6 py-3.5 font-bold transition hover:bg-white/10">Entender como funciona</Link></div><p className="mt-4 text-xs text-slate-400">Indicação direta, validação antifraude e pagamento via Pix após aprovação.</p></div>
          <div className="rounded-3xl border border-white/10 bg-white/[.07] p-6 shadow-2xl shadow-blue-950/30 sm:p-8"><div className="flex items-center gap-3"><Gift className="size-6 text-blue-300" /><h2 className="text-xl font-bold">Quanto você recebe</h2></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white p-5 text-slate-950"><p className="text-sm font-semibold text-slate-500">Conversão Pro</p><p className="mt-2 text-3xl font-black">R$ 25</p><p className="mt-1 text-sm text-slate-600">por indicação elegível</p></div><div className="rounded-2xl bg-blue-400 p-5 text-slate-950"><p className="text-sm font-semibold text-blue-950/70">Conversão Business</p><p className="mt-2 text-3xl font-black">R$ 70</p><p className="mt-1 text-sm text-blue-950/70">por indicação elegível</p></div></div><div className="mt-6 space-y-3 text-sm text-slate-300"><p className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0 text-blue-300" />Uma indicação direta por pessoa indicada.</p><p className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0 text-blue-300" />Acompanhamento no painel do parceiro.</p><p className="flex gap-2"><Check className="mt-0.5 size-4 shrink-0 text-blue-300" />Pagamento manual via Pix depois da conferência.</p></div></div>
        </div>
      </section>
      <section className="bg-white px-5 py-16 text-slate-950 sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-700">UM CAMINHO SIMPLES DE ACOMPANHAR</p><h2 className="mt-3 max-w-2xl text-3xl font-black tracking-tight sm:text-4xl">Da primeira indicação à confirmação do pagamento</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{stages.map(([number, title, text]) => <div key={number} className="rounded-2xl border border-slate-200 p-6"><span className="flex size-9 items-center justify-center rounded-full bg-blue-600 font-black text-white">{number}</span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-2 leading-7 text-slate-600">{text}</p></div>)}</div></div></section>
      <section className="mx-auto max-w-6xl px-5 py-16 sm:px-8"><div className="grid gap-5 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[.06] p-6"><Users className="size-6 text-blue-300" /><h2 className="mt-4 font-bold">Para quem indica com contexto</h2><p className="mt-2 text-sm leading-6 text-slate-300">Profissionais, agências, comunidades e parceiros que conhecem pessoas procurando serviços.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.06] p-6"><Wallet className="size-6 text-blue-300" /><h2 className="mt-4 font-bold">Regra objetiva</h2><p className="mt-2 text-sm leading-6 text-slate-300">O valor depende do plano pago pela pessoa indicada e só é liberado depois da validação.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.06] p-6"><ShieldCheck className="size-6 text-blue-300" /><h2 className="mt-4 font-bold">Sem promessas confusas</h2><p className="mt-2 text-sm leading-6 text-slate-300">Não existe cadeia de indicações. A equipe confere cada conversão antes de autorizar o Pix.</p></div></div></section>
      <section id="como-funciona" className="bg-slate-900 px-5 py-16 sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-300">COMO FUNCIONA</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Você não precisa divulgar sozinho</h2><p className="mt-4 max-w-2xl leading-7 text-slate-300">O painel organiza os registros. A aprovação depende do pagamento confirmado, da atribuição correta e das regras do programa.</p><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{steps.map(([title, text], index) => <div key={title} className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><span className="text-sm font-black text-blue-300">0{index + 1}</span><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{text}</p></div>)}</div></div></section>
      <section className="mx-auto grid max-w-6xl gap-8 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_.8fr]"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-300">REGRAS E TRANSPARÊNCIA</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">A recompensa é aprovada antes de ser paga</h2><div className="mt-6 space-y-4 text-slate-300"><p>O cadastro da indicação precisa estar atribuído ao seu link e não pode duplicar outro registro válido.</p><p>O primeiro pagamento do plano precisa ser aprovado. Depois, a equipe verifica elegibilidade, cancelamento e possíveis duplicidades.</p><p>O painel mostra o status. O Pix é feito manualmente pela equipe após a aprovação; não há saque automático prometido.</p></div></div><div className="rounded-3xl border border-white/10 bg-white/[.06] p-7"><h3 className="text-xl font-bold">Perguntas rápidas</h3><div className="mt-6 space-y-5 text-sm"><div><p className="font-bold">Preciso pagar para participar?</p><p className="mt-1 text-slate-300">Não. Você precisa ter uma conta e seguir as regras do programa.</p></div><div><p className="font-bold">Posso indicar clientes e profissionais?</p><p className="mt-1 text-slate-300">Sim, desde que a pessoa tenha interesse real e use seu link.</p></div><div><p className="font-bold">Quando recebo?</p><p className="mt-1 text-slate-300">Após pagamento aprovado e validação manual da conversão.</p></div></div></div></section>
      <section id="inscricao" className="bg-blue-600 px-5 py-16 sm:px-8"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-100">PRÓXIMO PASSO</p><h2 className="mt-3 max-w-2xl text-3xl font-black tracking-tight sm:text-4xl">Pronto para fazer sua primeira indicação?</h2><p className="mt-3 max-w-xl text-blue-100">Crie sua conta, gere o link no painel e comece por uma pessoa para quem a plataforma realmente pode ajudar.</p></div><Link href="/register?next=%2Fdashboard%2Freferral" className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-white px-6 py-3.5 font-bold text-blue-700 transition hover:bg-blue-50">Quero entrar no programa <ArrowRight className="size-5" /></Link></div></section>
      <footer className="border-t border-white/10 px-5 py-8 text-center text-sm text-slate-400"><Link href="/termos-indicacoes" className="hover:text-white">Termos do programa de indicações</Link></footer>
    </main>
  );
}

