// CERTO ECOSYSTEM - 27 PRODUTOS CONFIG
// Centraliza preços, links Assinify, MRR, status de todos os produtos

export interface ProductConfig {
  id: number;
  slug: string;
  name: string;
  icon: string;
  description: string;
  category: "matching" | "pricing" | "timing" | "intelligence" | "tools" | "payments" | "education" | "visibility" | "tier" | "application-enhancement";
  phase: 1 | 2 | 3 | 4;
  status: "live" | "building" | "planned";
  pricingType: "monthly" | "one-time" | "per-proposal" | "per-application" | "commission" | "free";
  price: number;
  currency: "BRL";
  mrr: number; // Projeção de MRR em R$
  assinifyUrl: string | null;
  setupInstructions?: string[];
}

export const CERTO_PRODUCTS: ProductConfig[] = [
  // ===== FASE 1: TOP 3 (Week 1-2) =====
  {
    id: 1,
    slug: "match",
    name: "CERTO MATCH",
    icon: "🎯",
    description: "IA Matching - Descubra sua chance de ganhar cada projeto",
    category: "matching",
    phase: 1,
    status: "live",
    pricingType: "per-proposal",
    price: 5.0,
    currency: "BRL",
    mrr: 2900,
    assinifyUrl: "https://assinify.com.br/certo-match",
  },
  {
    id: 2,
    slug: "preco",
    name: "CERTO PREÇO",
    icon: "💰",
    description: "Dynamic Pricing - Recomendação de preço ótimo baseado em IA",
    category: "pricing",
    phase: 1,
    status: "building",
    pricingType: "monthly",
    price: 14.9,
    currency: "BRL",
    mrr: 22000,
    assinifyUrl: "https://assinify.com.br/certo-preco",
  },
  {
    id: 3,
    slug: "timing",
    name: "CERTO TIMING",
    icon: "⏰",
    description: "Hora de Ouro - Melhor momento para enviar suas propostas",
    category: "timing",
    phase: 1,
    status: "building",
    pricingType: "monthly",
    price: 9.9,
    currency: "BRL",
    mrr: 18000,
    assinifyUrl: "https://assinify.com.br/certo-timing",
  },

  // ===== FASE 2: INTELIGÊNCIA (Week 3-6) =====
  {
    id: 4,
    slug: "dashboard-ia",
    name: "DASHBOARD IA",
    icon: "📊",
    description: "Dashboard inteligente com Match, Pricing, Timing, Insights",
    category: "intelligence",
    phase: 2,
    status: "planned",
    pricingType: "monthly",
    price: 49.9,
    currency: "BRL",
    mrr: 74850,
    assinifyUrl: "https://assinify.com.br/certo-dashboard-ia",
  },
  {
    id: 5,
    slug: "insights",
    name: "INSIGHTS",
    icon: "🔍",
    description: "Market Intelligence - Skills trending, salários, competição",
    category: "intelligence",
    phase: 2,
    status: "planned",
    pricingType: "monthly",
    price: 24.9,
    currency: "BRL",
    mrr: 37425,
    assinifyUrl: "https://assinify.com.br/certo-insights",
  },
  {
    id: 6,
    slug: "badge",
    name: "BADGE",
    icon: "🏆",
    description: "Badges verificadas - Top Performer, Verified Pro, Trending",
    category: "intelligence",
    phase: 2,
    status: "planned",
    pricingType: "monthly",
    price: 19.9,
    currency: "BRL",
    mrr: 29850,
    assinifyUrl: "https://assinify.com.br/certo-badge",
  },
  {
    id: 7,
    slug: "certificacao",
    name: "CERTIFICAÇÃO",
    icon: "📜",
    description: "Skills Certification - Mini-teste + projeto + review",
    category: "intelligence",
    phase: 2,
    status: "planned",
    pricingType: "one-time",
    price: 29.9,
    currency: "BRL",
    mrr: 44850,
    assinifyUrl: "https://assinify.com.br/certo-certificacao",
  },
  {
    id: 8,
    slug: "biblioteca-proposta",
    name: "BIBLIOTECA PROPOSTA",
    icon: "📚",
    description: "Histórico de propostas vencedoras (privadas)",
    category: "intelligence",
    phase: 2,
    status: "planned",
    pricingType: "monthly",
    price: 19.9,
    currency: "BRL",
    mrr: 29850,
    assinifyUrl: "https://assinify.com.br/certo-biblioteca-proposta",
  },
  {
    id: 9,
    slug: "portfolio-ia",
    name: "PORTFOLIO IA",
    icon: "🎨",
    description: "Portfolio auto-gerado de seus melhores projetos",
    category: "intelligence",
    phase: 2,
    status: "planned",
    pricingType: "monthly",
    price: 12.9,
    currency: "BRL",
    mrr: 19350,
    assinifyUrl: "https://assinify.com.br/certo-portfolio-ia",
  },
  {
    id: 10,
    slug: "followup-ia",
    name: "FOLLOW-UP IA",
    icon: "📧",
    description: "Auto-sequência inteligente de follow-ups (dia 3, 5, 7)",
    category: "intelligence",
    phase: 2,
    status: "planned",
    pricingType: "monthly",
    price: 12.9,
    currency: "BRL",
    mrr: 19350,
    assinifyUrl: "https://assinify.com.br/certo-followup-ia",
  },
  {
    id: 11,
    slug: "contraproposta-ia",
    name: "CONTRA-PROPOSTA IA",
    icon: "💬",
    description: "Gera contra-propostas profissionais baseado em orçamento",
    category: "intelligence",
    phase: 2,
    status: "planned",
    pricingType: "monthly",
    price: 9.9,
    currency: "BRL",
    mrr: 14850,
    assinifyUrl: "https://assinify.com.br/certo-contraproposta-ia",
  },

  // ===== FASE 3: CLIENT TOOLS (Week 7-10) =====
  {
    id: 12,
    slug: "curriculo",
    name: "CURRÍCULO",
    icon: "📋",
    description: "Seu currículo no PrestaCerto (otimizado, com histórico)",
    category: "tools",
    phase: 3,
    status: "planned",
    pricingType: "free",
    price: 0,
    currency: "BRL",
    mrr: 0,
    assinifyUrl: null,
  },
  {
    id: 13,
    slug: "escrow",
    name: "ESCROW",
    icon: "🔐",
    description: "Pagamento seguro com intermediário",
    category: "payments",
    phase: 3,
    status: "planned",
    pricingType: "commission",
    price: 5,
    currency: "BRL",
    mrr: 74500,
    assinifyUrl: null,
  },
  {
    id: 14,
    slug: "milestones",
    name: "MILESTONES",
    icon: "📍",
    description: "Pagamento por etapa de projeto",
    category: "payments",
    phase: 3,
    status: "planned",
    pricingType: "commission",
    price: 5.9,
    currency: "BRL",
    mrr: 29800,
    assinifyUrl: null,
  },
  {
    id: 15,
    slug: "analytics-cliente",
    name: "ANALYTICS CLIENTE",
    icon: "📈",
    description: "Dashboard para cliente ver progresso do projeto",
    category: "tools",
    phase: 3,
    status: "planned",
    pricingType: "monthly",
    price: 49.9,
    currency: "BRL",
    mrr: 74850,
    assinifyUrl: "https://assinify.com.br/certo-analytics-cliente",
  },
  {
    id: 16,
    slug: "contrato-ia",
    name: "CONTRATO IA",
    icon: "⚖️",
    description: "Contrato automático gerado por IA",
    category: "tools",
    phase: 3,
    status: "planned",
    pricingType: "monthly",
    price: 24.9,
    currency: "BRL",
    mrr: 37425,
    assinifyUrl: "https://assinify.com.br/certo-contrato-ia",
  },
  {
    id: 17,
    slug: "qa-automatico",
    name: "QA AUTOMÁTICO",
    icon: "🧪",
    description: "Teste automático de website/design antes de aprovar",
    category: "tools",
    phase: 3,
    status: "planned",
    pricingType: "monthly",
    price: 34.9,
    currency: "BRL",
    mrr: 52350,
    assinifyUrl: "https://assinify.com.br/certo-qa-automatico",
  },
  {
    id: 18,
    slug: "vip-network",
    name: "VIP NETWORK",
    icon: "👑",
    description: "Network exclusivo com leads premium (R$ 5k+)",
    category: "tools",
    phase: 3,
    status: "planned",
    pricingType: "monthly",
    price: 999.9,
    currency: "BRL",
    mrr: 1499850,
    assinifyUrl: "https://assinify.com.br/certo-vip-network",
  },
  {
    id: 19,
    slug: "community",
    name: "COMMUNITY",
    icon: "💬",
    description: "Discord/Slack privado com networking",
    category: "tools",
    phase: 3,
    status: "planned",
    pricingType: "monthly",
    price: 39.9,
    currency: "BRL",
    mrr: 59850,
    assinifyUrl: "https://assinify.com.br/certo-community",
  },

  // ===== FASE 4: COMUNIDADE (Week 11-14) =====
  {
    id: 20,
    slug: "academy",
    name: "ACADEMY",
    icon: "🎓",
    description: "Cursos online com certificados",
    category: "education",
    phase: 4,
    status: "planned",
    pricingType: "one-time",
    price: 297,
    currency: "BRL",
    mrr: 445500,
    assinifyUrl: "https://assinify.com.br/certo-academy",
  },
  {
    id: 21,
    slug: "templates",
    name: "TEMPLATES",
    icon: "📄",
    description: "Biblioteca de templates (propostas, contracts, etc)",
    category: "education",
    phase: 4,
    status: "planned",
    pricingType: "monthly",
    price: 29.9,
    currency: "BRL",
    mrr: 44850,
    assinifyUrl: "https://assinify.com.br/certo-templates",
  },
  {
    id: 22,
    slug: "invoice",
    name: "INVOICE",
    icon: "🧾",
    description: "NF-e automática integrado com Supabase",
    category: "payments",
    phase: 4,
    status: "planned",
    pricingType: "monthly",
    price: 19.9,
    currency: "BRL",
    mrr: 29850,
    assinifyUrl: "https://assinify.com.br/certo-invoice",
  },
  {
    id: 23,
    slug: "cold-email",
    name: "COLD EMAIL",
    icon: "✉️",
    description: "IA gera emails personalizados para conseguir projetos",
    category: "education",
    phase: 4,
    status: "planned",
    pricingType: "monthly",
    price: 59.9,
    currency: "BRL",
    mrr: 119850,
    assinifyUrl: "https://assinify.com.br/certo-cold-email",
  },
  {
    id: 24,
    slug: "tax",
    name: "TAX",
    icon: "💳",
    description: "Cálculo automático de IR + INSS",
    category: "payments",
    phase: 4,
    status: "live",
    pricingType: "monthly",
    price: 49.9,
    currency: "BRL",
    mrr: 74850,
    assinifyUrl: "https://assinify.com.br/certo-tax",
  },
  {
    id: 25,
    slug: "destaque",
    name: "DESTAQUE",
    icon: "⭐",
    description: "Destaque pago na busca (como Featured Projects)",
    category: "visibility",
    phase: 4,
    status: "planned",
    pricingType: "monthly",
    price: 79.9,
    currency: "BRL",
    mrr: 149850,
    assinifyUrl: "https://assinify.com.br/certo-destaque",
  },
  {
    id: 26,
    slug: "candidato-cliente",
    name: "CANDIDATO CLIENTE",
    icon: "🎯",
    description: "IA filtra e apresenta os 10 melhores candidatos para cada proposta",
    category: "visibility",
    phase: 4,
    status: "planned",
    pricingType: "per-proposal",
    price: 19.9,
    currency: "BRL",
    mrr: 29850,
    assinifyUrl: "https://assinify.com.br/certo-candidato-cliente",
  },
  {
    id: 27,
    slug: "candidato-freelancer",
    name: "CANDIDATO FREELANCER",
    icon: "🎯",
    description: "Apareça entre os 10 melhores candidatos para seus skills",
    category: "visibility",
    phase: 4,
    status: "planned",
    pricingType: "monthly",
    price: 9.9,
    currency: "BRL",
    mrr: 14850,
    assinifyUrl: "https://assinify.com.br/certo-candidato-freelancer",
  },
  {
    id: 28,
    slug: "certo-premium",
    name: "CERTO PREMIUM",
    icon: "🌟",
    description: "Tier premium para top performers (badge especial, boost)",
    category: "tier",
    phase: 4,
    status: "planned",
    pricingType: "monthly",
    price: 99.9,
    currency: "BRL",
    mrr: 149850,
    assinifyUrl: "https://assinify.com.br/certo-premium",
  },
  {
    id: 29,
    slug: "curriculum",
    name: "CERTO CURRICULUM",
    icon: "📄",
    description: "IA otimiza seu currículo customizado para cada vaga",
    category: "application-enhancement",
    phase: 3,
    status: "planned",
    pricingType: "per-application",
    price: 29.9,
    currency: "BRL",
    mrr: 44850,
    assinifyUrl: "https://pay.assiny.com.br/-U2V3I/node/TRU4zl",
  },
];

// Helpers
export function getProductBySlug(slug: string): ProductConfig | undefined {
  return CERTO_PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByPhase(phase: 1 | 2 | 3 | 4): ProductConfig[] {
  return CERTO_PRODUCTS.filter((p) => p.phase === phase);
}

export function getTotalMRR(): number {
  return CERTO_PRODUCTS.reduce((sum, p) => sum + p.mrr, 0);
}

export function getLiveProducts(): ProductConfig[] {
  return CERTO_PRODUCTS.filter((p) => p.status === "live");
}

export function getProductsByCategory(
  category: ProductConfig["category"]
): ProductConfig[] {
  return CERTO_PRODUCTS.filter((p) => p.category === category);
}

export function getAssinifyLinks(): { [key: string]: string } {
  const links: { [key: string]: string } = {};
  CERTO_PRODUCTS.forEach((p) => {
    if (p.assinifyUrl) {
      links[p.slug] = p.assinifyUrl;
    }
  });
  return links;
}
