'use client';
/* eslint-disable @next/next/no-html-link-for-pages */
import { useMemo, useState } from 'react';

type LeadStatus = 'Novo' | 'Em conversa' | 'Visita' | 'Aguardando';
type Lead = { id:number; name:string; initials:string; detail:string; source:string; score:number; status:LeadStatus; action:string; age:string };
const initialLeads: Lead[] = [
  {id:1,name:'Paulo Mendes',initials:'PM',detail:'Visita terça · 16h · Jardins',source:'WhatsApp',score:83,status:'Visita',action:'Confirmar visita',age:'há 12 min'},
  {id:2,name:'Fernanda Costa',initials:'FC',detail:'2–3 quartos · Gonzaga · até R$ 850 mil',source:'Site',score:80,status:'Em conversa',action:'Retomar com 1204',age:'há 18 min'},
  {id:3,name:'Ricardo Alves',initials:'RA',detail:'Casa · Enseada · investir',source:'Portal',score:61,status:'Aguardando',action:'Enviar comparativo',age:'há 3 h'},
  {id:4,name:'Camila Prado',initials:'CP',detail:'2 dorms · Jardins · portal',source:'Portal',score:40,status:'Novo',action:'Fazer primeira resposta',age:'há 7 min'},
  {id:5,name:'Lívia Nunes',initials:'LN',detail:'Apartamento · Santos · locação',source:'Instagram',score:55,status:'Em conversa',action:'Qualificar faixa',age:'há 42 min'},
];
const statusClass:Record<LeadStatus,string> = {Novo:'new', 'Em conversa':'talking', Visita:'visit', Aguardando:'waiting'};

export default function DashboardClient({userName,userEmail}:{userName:string;userEmail:string}) {
  const [leads,setLeads] = useState(initialLeads); const [filter,setFilter] = useState<'Todos'|LeadStatus>('Todos'); const [query,setQuery] = useState(''); const [selected,setSelected] = useState(1); const [notice,setNotice] = useState('');
  const visible = useMemo(()=>leads.filter(l=>(filter==='Todos'||l.status===filter)&&(l.name+' '+l.detail).toLowerCase().includes(query.toLowerCase())),[leads,filter,query]);
  const current = visible.find(l=>l.id===selected) ?? visible[0] ?? leads[0];
  const moveLead = () => { setLeads(items=>items.map(l=>l.id===current.id?{...l,status:l.status==='Visita'?'Em conversa':'Visita',action:l.status==='Visita'?'Definir próximo passo':'Visita confirmada'}:l)); setNotice(current.name + ': atualização registrada nesta sessão.'); };
  const markDone = () => { const next = leads.find(l=>l.id!==current.id); setLeads(items=>items.filter(l=>l.id!==current.id)); setSelected(next?.id ?? 1); setNotice(current.name + ': ação concluída.'); };
  const visits = leads.filter(l=>l.status==='Visita').length; const fresh = leads.filter(l=>l.status==='Novo').length;
  return <main className="portal-shell">
    <aside className="portal-sidebar"><a href="/" className="portal-brand"><span className="brand-mark">C</span><span>Cadu.</span></a><div className="workspace"><span className="workspace-symbol">A</span><div><strong>Atlântica Imóveis</strong><small>Operação ativa</small></div><span>⌄</span></div><nav className="portal-nav" aria-label="Navegação do portal"><a className="active" href="#visao">⌘ <span>Visão geral</span></a><a href="#fila">↗ <span>Fila de leads</span><b>{leads.length}</b></a><a href="#visitas">◷ <span>Visitas</span></a><a href="#insights">✦ <span>Insights</span></a><a href="#integracoes">⟐ <span>Integrações</span></a></nav><div className="portal-help"><strong>Precisa de ajuda?</strong><p>Fale com o time Cadu.</p><a href="https://wa.me/5513988251275" target="_blank" rel="noreferrer">Abrir WhatsApp ↗</a></div><a className="portal-user" href="/signout-with-chatgpt?return_to=/"><span>{userName.slice(0,2).toUpperCase()}</span><div><strong>{userName}</strong><small>{userEmail}</small></div><i>↗</i></a></aside>
    <section className="portal-content"><header className="portal-top"><div><p>OPERAÇÃO CADU</p><h1>Bom dia, {userName.split(' ')[0]}.</h1><span>Tem <strong>{fresh} leads novos</strong> e <strong>{visits} visitas</strong> pedindo atenção hoje.</span></div><div className="top-actions"><button aria-label="Notificações">◉</button><button className="primary-action" onClick={()=>setNotice('Resumo atualizado agora.')}>Atualizar agora ↻</button><a href="/signout-with-chatgpt?return_to=/" className="logout-btn" aria-label="Sair">Sair</a></div></header>
      {notice && <div className="portal-notice" role="status">✓ {notice}<button onClick={()=>setNotice('')} aria-label="Fechar aviso">×</button></div>}
      <section id="visao" className="portal-metrics"><Metric icon="↗" tone="coral" label="Leads recebidos" value="38" change="+12%" detail="vs. semana anterior"/><Metric icon="◷" tone="purple" label="Visitas agendadas" value="12" change="+3" detail="nesta semana"/><Metric icon="✓" tone="green" label="Primeira resposta" value="42s" change="−18s" detail="mais rápido"/><Metric icon="✦" tone="yellow" label="Taxa de avanço" value="31%" change="+4.2pp" detail="mês atual"/></section>
      <section className="portal-grid"><article className="funnel-card"><header><div><p>FUNIL DA OPERAÇÃO</p><h2>O que está acontecendo agora.</h2></div><button>Últimos 7 dias⌄</button></header><div className="funnel-bars">{[['Leads recebidos',38,'100%'],['Em conversa',27,'71%'],['Qualificados',18,'47%'],['Visitas agendadas',12,'31%'],['Visitas realizadas',8,'21%']].map((item,i)=><div className="funnel-row" key={item[0]}><div><span>{i+1}</span><strong>{item[0]}</strong></div><div className="bar"><i style={{width:String(Number(item[1])/38*100)+'%'}} /></div><b>{item[1]}</b><small>{item[2]}</small></div>)}</div><footer><span>✓ Dados demonstrativos — conecte seu CRM para ver a operação real.</span><a href="#integracoes">Ver integrações ↗</a></footer></article>
        <article id="visitas" className="agenda-card"><header><div><p>PRÓXIMAS VISITAS</p><h2>O dia em movimento.</h2></div><a href="#fila">Ver agenda ↗</a></header><div className="agenda-list">{[['10:30','Fernanda Costa','Apt. 1204 · Ana Costa','Confirmada'],['14:00','Paulo Mendes','Apartamento 82 · Haddock Lobo','Confirmar'],['16:30','Camila Prado','Casa Enseada','Em preparação']].map((v,i)=><article key={v[0]}><time>{v[0]}</time><div><strong>{v[1]}</strong><small>{v[2]}</small></div><span className={i===0?'confirmed':''}>{v[3]}</span></article>)}</div></article></section>
      <section id="fila" className="lead-queue"><header><div><p>FILA DE PRIORIDADE</p><h2>Quem sua equipe atende primeiro.</h2></div><div className="queue-controls"><label className="search"><span>⌕</span><input aria-label="Buscar leads" placeholder="Buscar lead" value={query} onChange={e=>setQuery(e.target.value)}/></label><button>Filtros ⌄</button></div></header><div className="filter-tabs">{(['Todos','Novo','Em conversa','Visita','Aguardando'] as const).map(item=><button className={filter===item?'selected':''} onClick={()=>setFilter(item)} key={item}>{item}{item==='Todos'&&<b>{leads.length}</b>}</button>)}</div><div className="queue-layout"><div className="lead-table" role="list">{visible.map((lead,index)=><button role="listitem" className={selected===lead.id?'selected':''} onClick={()=>setSelected(lead.id)} key={lead.id}><span className="rank">{String(index+1).padStart(2,'0')}</span><span className="lead-avatar">{lead.initials}</span><div className="lead-name"><strong>{lead.name}</strong><small>{lead.detail}</small></div><span className={'source '+lead.source.toLowerCase()}>{lead.source}</span><span className={'status '+statusClass[lead.status]}>{lead.status}</span><div className="lead-action"><strong>{lead.action}</strong><small>{lead.age}</small></div><b className="lead-score">{lead.score}</b></button>)}{visible.length===0&&<p className="empty-state">Nenhum lead encontrado neste filtro.</p>}</div><aside className="lead-detail"><header><span className="lead-avatar large">{current.initials}</span><div><h3>{current.name}</h3><p>{current.detail}</p></div><b className="lead-score">{current.score}</b></header><div className="detail-tags"><span>Intenção clara</span><span>Região definida</span><span>Faixa de orçamento</span></div><div className="detail-section"><p>PRÓXIMA AÇÃO</p><strong>{current.action}</strong><span>O Cadu deixou o contexto organizado para a equipe agir.</span></div><div className="detail-section"><p>ÚLTIMA MENSAGEM</p><blockquote>“Gostei da opção. Consigo visitar no período da tarde?”</blockquote><small>Hoje, 09:48 · Conversa via {current.source}</small></div><div className="detail-buttons"><button className="primary-action" onClick={moveLead}>Marcar visita</button><button onClick={markDone}>Concluir ação ✓</button></div></aside></div></section>
      <section id="insights" className="insight-banner"><div><p>INSIGHT DA SEMANA</p><h2>Leads com visita no radar avançam <em>2,3× mais</em> quando recebem confirmação no mesmo dia.</h2></div><button onClick={()=>setNotice('Lembrete de confirmação preparado para sua operação.')}>Ativar lembrete ↗</button></section>
      <section id="integracoes" className="portal-integrations"><div><p>INTEGRAÇÕES</p><h2>Conecte a operação real.</h2><span>O dashboard já está pronto; basta ligar as fontes para trocar os dados demonstrativos pelos dados da sua imobiliária.</span></div><div><article><span>V</span><strong>Vista CRM</strong><small>Em homologação</small></article><article><span>RD</span><strong>RD Station</strong><small>Em homologação</small></article><article><span>W</span><strong>WhatsApp oficial</strong><small>Próxima etapa</small></article></div></section>
    </section>
  </main>;
}
function Metric({icon,tone,label,value,change,detail}:{icon:string;tone:string;label:string;value:string;change:string;detail:string}) { return <article><span className={'metric-icon '+tone}>{icon}</span><div><p>{label}</p><strong>{value}</strong><small className="up">{change} <i>{detail}</i></small></div><div className={'sparkline '+tone} /></article>; }
