const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,overrides={}){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:m,exports:m.exports,Buffer,URL,Response,Request,AbortSignal,Date,console,process:{env:{}},fetch,require(name){if(name in overrides)return overrides[name];if(name.startsWith('node:'))return require(name);throw Error(name)}});return m.exports}
const knowledge=load('src/lib/support/knowledge.ts',{'@/lib/plans-data':{PLANS:[{name:'Grátis',priceMonthly:0,features:['3 propostas']}]}});
const chat=load('src/lib/support/chat.ts',{'./knowledge':knowledge});
const settings={url:'https://sima.example/chat',key:'a'.repeat(64),tenant:'prestacerto',model:'gpt-4.1-mini'};
test('distributed immutable reservations stay within cap under 100 concurrent calls',async()=>{const objects=new Set();const storage={getBucket:async()=>({data:{public:false}}),from:()=>({upload:async path=>{if(objects.has(path))return {error:{message:'The resource already exists',statusCode:'409'}};objects.add(path);return {error:null}}})};const store=load('src/lib/support/storage.ts',{'server-only':{},'@/lib/supabase/service':{createServiceClient:()=>({storage})}});const results=await Promise.all(Array.from({length:100},()=>store.reserveSupport('same-ip')));assert.ok(results.filter(Boolean).length<=15);assert.ok(results.filter(Boolean).length>0)});
test('storage upstream throttle is a denied reservation, not a generic server exception',async()=>{const storage={getBucket:async()=>({data:{public:false}}),from:()=>({upload:async()=>({error:{message:'Too many requests',statusCode:'429'}})})};const store=load('src/lib/support/storage.ts',{'server-only':{},'@/lib/supabase/service':{createServiceClient:()=>({storage})}});assert.equal(await store.reserveSupport('ip'),false)});
test('configuration fails closed and rejects non-HTTPS endpoints',()=>{assert.equal(chat.supportSettings({}),null);assert.equal(chat.supportSettings({SIMA_AI_API_URL:'http://localhost',SIMA_AI_API_KEY:'key',SIMA_AI_TENANT_ID:'tenant',SIMA_AI_MODEL:'model'}),null)});
test('history is signed and bound to tenant, audience and credential',()=>{const token=chat.signHistory([{role:'user',content:'oi'}],'client',settings);assert.equal(chat.readHistory(token,'client',settings).length,1);assert.throws(()=>chat.readHistory(token,'provider',settings));assert.throws(()=>chat.readHistory(token,'client',{...settings,tenant:'other'}));assert.throws(()=>chat.readHistory(token+'x','client',settings));assert.throws(()=>chat.readHistory(token,'client',{...settings,key:'other'}))});
test('provider error or wrong tenant never becomes success',async()=>{const input={message:'oi',audience:'client'};await assert.rejects(()=>chat.askSupport(input,settings,async()=>Response.json({error:'private diagnostic'},{status:500})));await assert.rejects(()=>chat.askSupport(input,settings,async()=>Response.json({tenant_id:'other',reply:'private content'})));await assert.rejects(()=>chat.askSupport(input,settings,async()=>Response.json({tenant_id:'prestacerto',reply:'x'.repeat(2100)})))});
test('100 concurrent isolated sessions: adapter load, not production capacity',async()=>{let active=0,peak=0;const durations=[];const start=performance.now();const answers=await Promise.all(Array.from({length:100},(_,i)=>(async()=>{const t=performance.now();const answer=await chat.askSupport({message:'session-'+i,audience:i%2?'client':'provider'},settings,async(url,init)=>{active++;peak=Math.max(peak,active);assert.equal(init.headers['X-Sima-Tenant-Id'],'prestacerto');const body=JSON.parse(init.body);assert.equal(body.tools.length,0);assert.equal(body.messages[0].role,'system');await new Promise(r=>setTimeout(r,30));active--;return Response.json({tenant_id:'prestacerto',reply:'Resposta '+body.messages.at(-1).content,usage:{input_tokens:100,output_tokens:20}})});durations.push(performance.now()-t);return answer})()));assert.equal(peak,100);assert.equal(new Set(answers.map(x=>x.history)).size,100);durations.sort((a,b)=>a-b);console.log(JSON.stringify({test:'adapter-mock-100',sessions:100,peak,errors:0,p50_ms:durations[49],p95_ms:durations[94],total_ms:performance.now()-start,provider_cost_usd:0,limitation:'mock transport, no production storage or model'}))});
test('engine rejects unauthenticated access before provider or storage',async()=>{let accessed=false;const engine=load('src/app/api/support/engine/route.ts',{'@/lib/http/request-body':{},'@/lib/support/storage':{recordSupport:()=>{accessed=true}},'@/lib/support/knowledge':knowledge});assert.equal((await engine.POST(new Request('https://prestacerto.com.br/api/support/engine',{method:'POST'}))).status,401);assert.equal(accessed,false)});
test('widget renders text, uses fixed CTAs, never ships credential names',()=>{const code=fs.readFileSync('src/components/support/cadu-widget.tsx','utf8');assert.doesNotMatch(code,/SIMA_AI_API_KEY|OPENAI_API_KEY|dangerouslySetInnerHTML/);assert.match(code,/result.success!==true/);assert.match(code,/Autorizo compartilhar/);assert.match(code,/AbortController/)});
