const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),crypto=require('node:crypto');
function moduleTS(file,overrides={}){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module:m,exports:m.exports,Buffer,URL,Request,Response,AbortSignal,Date,console,process:{env:{}},fetch,require(n){if(n in overrides)return overrides[n];if(n.startsWith('node:'))return require(n);throw Error(n)}});return m.exports}
const knowledge=moduleTS('src/lib/sima-engine/knowledge.ts');
const requestBody=moduleTS('src/lib/http/request-body.ts');
const config={prestacerto:{paths:['/plans'],audiences:['provider'],actions:[{type:'view_plans',label:'Ver planos',url:'/plans'}]},sinalmeet:{paths:['/checkout'],audiences:['company'],actions:[{type:'request_demo',label:'Demonstração',url:'/#contato'}]}};
function setup(delay=0){
 const count={},core=moduleTS('src/lib/sima-engine/core.ts',{'@/lib/http/request-body':requestBody,'./tenants':{tenants:config},'node:crypto':{...crypto,randomInt:n=>(count[n]=(count[n]??-1)+1)%n}}),maps={test:new Map(),production:new Map()};
 const keys={test:'t'.repeat(64),production:'p'.repeat(64),sinal:'s'.repeat(64)};
 const stores=Object.fromEntries(Object.entries(maps).map(([env,m])=>[env,{async read(k){return m.get(k)??null},async create(k,v){if(m.has(k))return false;m.set(k,structuredClone(v));return true},async remove(k){m.delete(k)},async latest(p){const k=[...m.keys()].filter(k=>k.startsWith(p+'/')).sort().at(-1);return k?m.get(k):null}}]));
 let calls=0;
 const deps={credentials:JSON.stringify([{tenant:'prestacerto',environment:'test',sha256:core.hash(keys.test)},{tenant:'prestacerto',environment:'production',sha256:core.hash(keys.production)},{tenant:'sinalmeet',environment:'test',sha256:core.hash(keys.sinal)}]),store:async env=>stores[env],generate:async(tenant,audience,turns)=>{calls++;if(delay)await new Promise(r=>setTimeout(r,delay));return {text:'Resposta '+turns.at(-1).content,action_types:['view_plans','evil'],handoff_required:false,handoff_reason:null,handoff_summary:null,usage:{input_tokens:100,output_tokens:20}}}};
 const body=(message='oi')=>({message_id:crypto.randomUUID(),session_id:null,tenant:'prestacerto',message,page_context:{path:'/plans',audience:'provider'}});
 const send=(b,key=keys.test,env='test',extra={})=>core.handleEngine(new Request('https://engine.test/api/v1/engine/chat',{method:'POST',headers:{Authorization:'Bearer '+key,'content-type':'application/json','idempotency-key':b.message_id,...extra},body:JSON.stringify(b)}),env,deps);
 return {body,send,keys,maps,deps,get calls(){return calls}};
}
test('authentication, tenant and environment fail closed',async()=>{const h=setup(),b=h.body();assert.equal((await h.send(b,'bad')).status,401);assert.equal((await h.send(b,h.keys.test,'production')).status,403);assert.equal((await h.send({...b,tenant:'sinalmeet'})).status,403);assert.equal((await h.send(b,h.keys.test,'test',{Origin:'https://evil.test'})).status,403);assert.equal(h.calls,0)});
test('payload/context/idempotency validation is enforced before inference',async()=>{const h=setup(),b=h.body();assert.equal((await h.send({...b,page_context:{path:'//evil',audience:'provider'}})).status,400);assert.equal((await h.send({...b,message:'a'.repeat(8001)})).status,400);assert.equal((await h.send(b,h.keys.test,'test',{'Idempotency-Key':crypto.randomUUID()})).status,400);assert.equal(h.calls,0)});
test('100 concurrent duplicate deliveries invoke model once, retry replays original',async()=>{const h=setup(50),b=h.body();const responses=await Promise.all(Array.from({length:100},()=>h.send(b)));assert.equal(h.calls,1);assert.equal(responses.filter(r=>r.status===200).length,1);assert.ok(responses.every(r=>[200,202].includes(r.status)));const original=await responses.find(r=>r.status===200).json();const replay=await h.send(b);assert.equal(replay.status,200);assert.equal(replay.headers.get('Idempotency-Replayed'),'true');assert.deepEqual(await replay.json(),original);assert.equal(h.calls,1);assert.deepEqual(original.actions,[{type:'view_plans',label:'Ver planos',url:'/plans'}]);assert.equal((await h.send({...b,message:'changed'})).status,409)});
test('session is opaque, persistent and isolated by tenant/environment',async()=>{const h=setup();const first=await(await h.send(h.body())).json();assert.match(first.session_id,/^ses_[A-Za-z0-9_-]{32}$/);const next={...h.body(),session_id:first.session_id};assert.equal((await h.send(next)).status,200);assert.equal((await h.send(next,h.keys.production,'production')).status,404);assert.equal((await h.send({...next,tenant:'sinalmeet',page_context:{path:'/checkout',audience:'company'}},h.keys.sinal)).status,404)});
test('concurrent messages in one session do not overwrite history',async()=>{const h=setup(30),first=await(await h.send(h.body())).json();const results=await Promise.all([1,2].map(n=>h.send({...h.body('turn'+n),session_id:first.session_id})));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.equal(h.calls,2)});
test('provider failure is terminal for that message and never re-inferred',async()=>{const h=setup(),b=h.body();let calls=0;h.deps.generate=async()=>{calls++;throw Error('timeout')};assert.equal((await h.send(b)).status,504);assert.equal((await h.send(b)).status,504);assert.equal(calls,1)});
test('100 independent sessions concurrent, simulated provider, isolate results',async()=>{const h=setup(20),started=performance.now();const results=await Promise.all(Array.from({length:100},(_,i)=>h.send(h.body('session'+i))));assert.ok(results.every(r=>r.status===200));const bodies=await Promise.all(results.map(r=>r.json()));assert.equal(new Set(bodies.map(b=>b.session_id)).size,100);assert.equal(h.calls,100);console.log(JSON.stringify({test:'sima-engine-100-mock',sessions:100,errors:0,total_ms:performance.now()-started,note:'in-memory test storage and mock model, not production capacity'}))});
test('duplicate bursts reserve only one pair of quota slots',async()=>{const h=setup(20),b=h.body();await Promise.all(Array.from({length:100},()=>h.send(b)));assert.equal([...h.maps.test.keys()].filter(k=>k.includes('/quota/')).length,2);assert.equal(h.calls,1)});
test('multi-byte conversation history stays below the storage byte budget',async()=>{const h=setup();let session_id=null;h.deps.generate=async(t,a,turns)=>{assert.ok(Buffer.byteLength(JSON.stringify(turns))<=50000);return{text:'汉'.repeat(2000),action_types:[],handoff_required:false,handoff_reason:null,handoff_summary:null,usage:{input_tokens:10,output_tokens:10}}};for(let i=0;i<10;i++){const r=await h.send({...h.body('汉'.repeat(8000)),session_id});assert.equal(r.status,200);session_id=(await r.json()).session_id}for(const[k,v]of h.maps.test)if(k.includes('/turns/'))assert.ok(Buffer.byteLength(JSON.stringify(v))<51000)});
test('master knowledge preserves core commercial and tenant safety rules',()=>{const text=knowledge.simaMasterInstructions();assert.match(text,/tenant separado/i);assert.match(text,/não se misturam/i);assert.match(text,/não manipule/i);assert.match(text,/Upsell só quando/i);assert.match(text,/não confirma pagamento/i);assert.match(text,/Não mencionar "OpenAI", "ChatGPT"/i);assert.match(text,/PrestaCerto/i);assert.match(text,/SinalMeet/i);assert.match(text,/ChaveZero/i);assert.match(text,/Morvya/i)});
test('SinalMeet genius layer covers B2B depth without unsafe promises',()=>{const text=knowledge.sinalMeetGeniusKnowledge;assert.match(text,/ICP/i);assert.match(text,/Lead versus conta/i);assert.match(text,/B2B2C/i);assert.match(text,/Apollo já funciona/i);assert.match(text,/Google Ads está integrado/i);assert.match(text,/não prometer base pronta/i);assert.match(text,/sem prometer ROI/i);assert.match(text,/Growth/i);assert.match(text,/Scale/i);assert.match(text,/White Label/i);assert.match(text,/Matriz conceitual de negociação/i);assert.match(text,/handoff.required=true/i);assert.match(text,/voz brasileira neutra/i);assert.match(text,/WhatsApp e telefone são fases futuras/i);assert.match(text,/request_demo/i);assert.match(text,/Não inventar URL de cadastro/i)});
test('PrestaCerto genius layer covers marketplace conversion without unsafe promises',()=>{const text=knowledge.prestaCertoGeniusKnowledge;assert.match(text,/marketplace/i);assert.match(text,/publicar projeto/i);assert.match(text,/create_profile/i);assert.match(text,/publish_project/i);assert.match(text,/Certo Propostas/i);assert.match(text,/Certo AI/i);assert.match(text,/não há comissão/i);assert.match(text,/escrow/i);assert.match(text,/não garante aprovação/i);assert.match(text,/não há garantia/i);assert.match(text,/SinalMeet/i);assert.match(text,/ChaveZero/i);assert.match(text,/Morvya/i);assert.match(text,/Sima Creators/i);assert.match(text,/Selo pago indica plano/i)});
